version: '3'

services: 
    db:
        image: postgres:3.1
        restart: always
        environment:
            - POSTGRES_PASSWORD: postgres
            - POSTGRES_USER: postgres
        ports: 
            - '5432:5432'
        networks: 
            - frontend
    question-app:
        build: .
        ports: 
            - '3001:3000' 
        depends_on: 
            - db
        networks: 
            - frontend

networks: 
    frontend:
        # Use a custom driver
        driver: bridge 