version: '3'

services: 
    postgres:
        container_name: postgres
        image: postgres:13.1
        ports: 
            - 5432:5432 
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        networks: 
            - network-app
    question-app:
        container_name: question-app
        build: .
        ports: 
            - 3000:3000
        depends_on: 
            - postgres
        networks: 
            - network-app

networks: 
    network-app:
        name: network-app